### ISSUE TITLE
Re-running a prediction gives me a warning.

### ISSUE THREAD

**Issue by davies-w** [mljar/support#1]
Linear algorithm was disabled.
This model has already been fitted. You can use predict methods or select a new 'results_path' for a new 'fit()'.

UserWarning: X has feature names, but StandardScaler was fitted without feature names
 and is repeated 100x?

Any ideas? 

Thanks so much, a very helpful tool!
 W

**Comment by pplonski** [comment]
We are working on these warnings, they will be removed in the next version of AutoML. Please check latest commits by @a-szulc in https://github.com/mljar/mljar-supervised
