### ISSUE TITLE
HOWTO investigate the ROC curve?

### ISSUE THREAD

**Issue by davies-w** [mljar/support#3]
When I run the optimizer, I get a stacked Ensemble solution with around 70% AUC. However, when I run prediction, I get a mere 100 (out of 1000+) positive examples predicted. I'm guessing there's some threshold that gets better overall recall but with slightly less precision. Is there any way to ask for predictions to be done at a certain threshold of the ROC curve that you've produced

Thanks,
 W

**Comment by pplonski** [comment]
Hi @davies-w,

Thanks for message. Are you using MLJAR Studio? 

You are right for `predict()` we apply threshold that is optimizing selected metric. You can obtain raw predictions by running `predict_proba()` or `predict_all()` , here is docs https://supervised.mljar.com/api/#supervised.automl.AutoML.predict_proba

**Comment by davies-w** [comment]
Aha! Thank you, that's just what I needed!
